version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosysten: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
